"""
Markdown Report Generator for AutoPatch.

Generates a PR-ready markdown report from the agent's final_report JSON.
Used by:
  - CLI mode (GitHub Actions CI/CD)
  - API /api/report endpoint (for download)
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any


def generate_markdown_report(report: dict[str, Any], branch: str = "main") -> str:
    """Generate a markdown report suitable for a Pull Request body.

    Args:
        report: The final_report dict from the LangGraph agent.
        branch: The branch name fixes were applied to.

    Returns:
        A formatted markdown string.
    """
    fixes = report.get("fixes", [])
    successful = [f for f in fixes if f.get("status") == "success"]
    errored = [f for f in fixes if f.get("status") == "error"]
    flagged = [f for f in successful if f.get("flagged_by_judge")]

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []
    lines.append("## 🛡️ AutoPatch — Automated Code Correction Report")
    lines.append("")
    lines.append(f"**Generated:** {now}  ")
    lines.append(f"**Project:** `{report.get('project_key', 'unknown')}`  ")
    lines.append(f"**Branch:** `{branch}`  ")
    lines.append("")

    # ── Summary Table ────────────────────────────────────────────────────
    lines.append("### 📊 Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Issues Found | {len(report.get('original_issues_fetched', []))} |")
    lines.append(f"| Fixes Attempted | {report.get('total_fixes_attempted', 0)} |")
    lines.append(f"| **Fixes Successful** | **{len(successful)}** |")
    lines.append(f"| Fixes Failed | {len(errored)} |")
    lines.append(f"| ⚠️ Flagged for Review | {len(flagged)} |")
    lines.append(f"| Remaining Issues | {report.get('remaining_issues', 0)} |")
    lines.append("")

    # ── Per-File Details ─────────────────────────────────────────────────
    if successful:
        lines.append("### ✅ Fixes Applied")
        lines.append("")

        for fix in successful:
            file_path = fix.get("file_path", "unknown")
            details = fix.get("fix_details", [])
            iteration = fix.get("iteration_applied", 1)

            lines.append(f"#### 📄 `{file_path}`")
            if fix.get("flagged_by_judge"):
                lines.append(f"> ⚠️ **Judge Warning:** {fix.get('judge_rationale', 'Review carefully.')}")
            lines.append("")

            if details:
                lines.append("| Rule | Severity | What Changed | Benefit |")
                lines.append("|------|----------|-------------|---------|")
                for fd in details:
                    rule_id = fd.get("rule_id", "")
                    severity = fd.get("severity", "?")
                    what = fd.get("what_changed", "").replace("\n", " ")[:120]
                    benefit = fd.get("benefit", "").replace("\n", " ")[:120]
                    lines.append(f"| `{rule_id}` | {_severity_emoji(severity)} {severity} | {what} | {benefit} |")
                lines.append("")

                # Code diff snippets
                lines.append("<details>")
                lines.append("<summary>🔍 View code changes</summary>")
                lines.append("")
                for fd in details:
                    title = fd.get("issue_title", "Fix")
                    lines.append(f"**{title}** (`{fd.get('rule_id', '')}`)")
                    lines.append("")
                    lines.append(f"*Root cause:* {fd.get('root_cause', 'N/A')}")
                    lines.append("")
                    lines.append("```diff")
                    # Show before lines as removed
                    for line in (fd.get("original_snippet", "") or "").splitlines():
                        lines.append(f"- {line}")
                    # Show after lines as added
                    for line in (fd.get("fixed_snippet", "") or "").splitlines():
                        lines.append(f"+ {line}")
                    lines.append("```")
                    lines.append("")
                lines.append("</details>")
                lines.append("")

    # ── Failed Fixes ─────────────────────────────────────────────────────
    if errored:
        lines.append("### ❌ Failed Fixes")
        lines.append("")
        for fix in errored:
            file_path = fix.get("file_path", "unknown")
            message = fix.get("message", "Unknown error")[:200]
            lines.append(f"- `{file_path}`: {message}")
        lines.append("")

    # ── Footer ───────────────────────────────────────────────────────────
    lines.append("---")
    lines.append("")
    lines.append("*This PR was generated by [AutoPatch](https://github.com/Aasrith-Mandava/sonar-project) — an autonomous AI agent that detects and fixes code quality issues using SonarQube + LLMs.*")
    lines.append("")
    lines.append("> **Please review each change carefully before merging.** The agent preserves business logic, but human verification is essential.")
    lines.append("")

    return "\n".join(lines)


def generate_github_actions_summary(report: dict[str, Any]) -> str:
    """Generate a concise summary for GitHub Actions step summary ($GITHUB_STEP_SUMMARY).

    This appears in the Actions run summary tab.
    """
    fixes = report.get("fixes", [])
    successful = [f for f in fixes if f.get("status") == "success"]
    errored = [f for f in fixes if f.get("status") == "error"]

    lines: list[str] = []
    lines.append("# 🛡️ AutoPatch Run Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Project | `{report.get('project_key', '?')}` |")
    lines.append(f"| Issues Found | {len(report.get('original_issues_fetched', []))} |")
    lines.append(f"| ✅ Fixed | {len(successful)} |")
    lines.append(f"| ❌ Failed | {len(errored)} |")
    lines.append(f"| Remaining | {report.get('remaining_issues', 0)} |")
    lines.append("")

    if successful:
        lines.append("## Files Fixed")
        lines.append("")
        for fix in successful:
            fp = fix.get("file_path", "?")
            count = len(fix.get("fix_details", []))
            lines.append(f"- ✅ `{fp}` — {count} issue{'s' if count != 1 else ''}")
        lines.append("")

    if errored:
        lines.append("## Files Failed")
        lines.append("")
        for fix in errored:
            fp = fix.get("file_path", "?")
            lines.append(f"- ❌ `{fp}` — {fix.get('message', '?')[:100]}")
        lines.append("")

    return "\n".join(lines)


def _severity_emoji(severity: str) -> str:
    """Map severity to an emoji."""
    mapping = {
        "bug": "🐛",
        "vulnerability": "🔓",
        "code smell": "🧹",
        "code_smell": "🧹",
        "security hotspot": "🔥",
        "security_hotspot": "🔥",
        "critical": "🔴",
        "blocker": "🔴",
        "major": "🟡",
        "minor": "🟢",
        "info": "⚪",
    }
    return mapping.get(severity.lower(), "📌")
